### ISSUE TITLE
Uploading images directly to Paperize

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#13]
**Is your feature request related to a problem? Please describe.**
I usually will go online and search for icons or images for the prototype and download them. Then, I will try to add them to Paperize, to realize that I first need to upload them to google drive.

**Describe the solution you'd like**
It would be great to have a simple interface to upload the images directly from your machine into paperize (which in turn would be uploading it to Google Drive or whatever image system it is). I know that there's no need to implement a robust image uploader, but it seems like it shouldn't be a super complicated issue to solve (there should be millions of plugins and libraries to do image uploading).

**Describe alternatives you've considered**
Being a bit less lazy and just uploading them to Google Drive first, XD.

**Comment by lorennorman** [comment]
This is the tip of the image iceberg, brace yourself.

Something we MUST do is decrease our Google Drive permissions. We're currently asking for `drive` access, which means "full access to everything", this is too much. We _could_ downgrade to `drive.readonly`, which means "read access to everything", but for my tastes, this is _still_ too much. What we need to be doing is `drive.file`, which means "access only to things this app put there"... _which is too little!_ 😦 

My plan was to leave Drive altogether for images (go to Dropbox/Imgur/Cloudinary etc.), and if we go that route then there's no reason to imagine doing this at all.

Another possible plan is to do this! I'm not against adding an image uploader to Paperize, it is certainly possible to do, but I expect it to be quite a task: lots of UI/UX to create and manage, users will need to be able to upload lots at once (entire directories), need to have control over where they go, etc. It won't be easy to get right, and it will have ongoing support implications. But it will work with `drive.file`, which is very valuable!

What WON'T work with `drive.file` is the user uploading images directly through the Google Drive interface: Paperize will _never_ be able to find those files (it works today due to the awful permissions we're using.) Is that UX just awful? Your images just don't work when you use Drive as intended, and instead you have to drag them over to Paperize to put hem in Drive?

So you see I'm not super sure about going forward with this, but let's keep talking about it.

This also addresses #6: if Paperize is doing the uploading, it will also know to index those files for finding later.

**Comment by lorennorman** [comment]
Ok taking a swipe at what is needed... 😓 

1. make a dang DebugMenu thinger for easy playing in dev mode
2. grab a simple Vue uploader-majig, check Vuetify as well, throw on DebugMenu
3. print out the filename(s) being imported
4. test simple, sequential uploading to Drive
5. can Paperize see the files under `drive.file` permission?

If this can be proven to work I'll get excited again and plan out the real implementation.

Off top of my head:
- how does user initiate upload? drag-n-drop? upload buttons around the site?
- background uploading? progress indicators? concurrency?
- where do images actually go? context-specific?
- automatic indexing by Drive Explorer (no refreshing required)

**Comment by lorennorman** [comment]
Oh my gosh, we actually shipped this awhile ago in #84! 🎉
