### ISSUE TITLE
Deep Linking doesn't work

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#22]
**Describe the bug**
Paperize always redirects to the app's root path, it should understand deep links into games, wait until the database is loaded, and attempt to actually load the game. If that fails, it can redirect to the root with an error message.

**To Reproduce**
1. Create a game
2. Open the game for editing, note the path `/games/abc123`
3. Refresh the browser
4. See the app redirect to the root instead of loading the game

**Expected behavior**
Should load the game identified by `abc123` for editing.

**Additional context**
This is a router concern, filter or something is overzealous in "fixing" the current route, assuming the empty database is "real" before the actual database is loaded.

**Comment by lorennorman** [comment]
I'm doing some auto-routing stuff after the regular routes that is likely the cause:
https://github.com/paperize/paperize/blob/master/lib/routes.js#L46-L84

It doesn't know how to wait until the database has been loaded before forcing the "splash" redirect, which loses the routing information in the URL.

I do not remember what the component re-use thing is about...

**Comment by riverole** [comment]
Mmmmmm. Looking into this. So, waiting for loading the store is not so bad (wrapping all in a:
 store.dispatch("whenStoreReady").then(() => {
However, the problem is that when refreshing the page, we're actually sending a couple of resetState actions, which are actually pushing the splash page. So we basically push 3 routes (the correct one and then 2 splash ones), which finally messes up the route and ends up in the home page. I'll investigate more, to see if pushing those splash pages it is necessary or if we can work around it somehow.

**Comment by riverole** [comment]
As I see it, there's two possible options to solve this:

1. If we get a resetState message we do not push any route.
2. We send different messages for the cases where we're sending the resetMessage now on refresh of a page, user.js and database.js, or the opposite ones. And then we do not push any routes on this case.

I guess there's other options, but to me these sound the more straightforward. In which cases do you think that a reset of the state will happen and we need to push a route which isn't the user loading paperize? Maybe it's easier to address these cases and manually push a route there, rather than always pushing a route every time there's a reset of state.

**Comment by lorennorman** [comment]
It sounds like we should disconnect `resetState` from forcing a route update. That sounds like something I needed to hack in for some other reason. I guess that's the question: what breaks if we do that?

Right now I think `resetState` is only used on login after the database is downloaded. But that could happen multiple times in one session (login, logout, login), not sure if that's meaningful.

In the future, when we get database backups and loading of different database versions, that code will need something similar. Maybe there are multiple versions of `resetState` or something.
