### ISSUE TITLE
Components are not showing the number of cards after clicking edit in a game

### ISSUE THREAD

**Issue by riverole** [paperize/paperize#4]
**Describe the bug**
Components are not showing the number of cards after clicking edit in a game. They will only show after I click on one of the components (at that point for both components it shows the number of cards and other info).

**To Reproduce**
1. Create a new game.
2. Create new components, with multiple cards each for the game.
3. Log out paperize.
4. Log in and click edit in your game.

**Expected behavior**
The components should show the number of cards that you already have, etc.

**Screenshots**
After clicking edit in the game, it shows no cards:
<img width="1129" alt="NoCardsForComponent" src="https://user-images.githubusercontent.com/4833422/73116083-7afc2800-3ee5-11ea-891f-e39b87e8ec29.png">
After selecting one of the components, they load:
<img width="1291" alt="CardsForComponent" src="https://user-images.githubusercontent.com/4833422/73116091-aa129980-3ee5-11ea-8000-780015913973.png">

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Browser: Chrome
 - Paperize Version: ver.A7.0.1

**Comment by lorennorman** [comment]
This is because we don't currently persist the spreadsheet data into the user's database, and we don't fetch it until they select a component.

Some possible things we can do:
- persist the spreadsheet: bloats the database but saves on API calls
- stop showing the number of items in the sidebar: instant change but worse UX (maybe)
- persist just the row count

Thoughts @riverole?

**Comment by riverole** [comment]
Actually, when are selecting one component we are loading the numbers for all of them at the same time. Why can't we just do that once we have opened the game page? Why do we need to wait until they select a specific component?
