### ISSUE TITLE
Copying Templates

### ISSUE THREAD

**Issue by lorennorman** [paperize/paperize#44]
When first opening the Template Editor on a new component, the empty Layer list could have an empty state that offers copying a template from an existing component, with a list of components to pick from.

This would copy every layer on the other template and associate the copied layers with this template.

**Comment by riverole** [comment]
So, I guess when opening the template for the same time, instead of showing all the stuff, I do a radio select (unchecked) for either create new template or copy from existing component, and then a list of all the component names? And if they select create, then the normal stuff to create layers appear, and if they select copy from existing, then when they select the component, then the normal stuff appears, with the layers prepopulated. How does that sound?

**Comment by lorennorman** [comment]
Sounds right to me!

For the future, think about how this will also be a great place to offer examples or starter templates or template templates or whatever. "Magic Card" with it all designed out already.

Should be a very similar mechanism, code-wise, we just gotta decide where we're going to store and retrieve all the example data.
